---
- name: ETSI MEC Sandbox Kubernetes Setup
  hosts: all
  become: true
  gather_facts: true
  vars:
    docker_version: "5:20.10.22~3-0~ubuntu-{{ ansible_distribution_release }}"
    docker_cli_version: "5:20.10.22~3-0~ubuntu-{{ ansible_distribution_release }}"
    containerd_version: "1.6.14-1"
    compose_plugin_version: "2.14.1~ubuntu-{{ ansible_distribution_release }}"
    user_name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    go_version: "1.17"
    go_tar: "go1.17.linux-amd64.tar.gz"
    go_url: "https://dl.google.com/go/go1.17.linux-amd64.tar.gz"
    node_version: "12.19.0"
    pip_packages:
      - pyyaml
    nvm_dir: "{{ ansible_env.HOME }}/.nvm"

  tasks:
    - name: Include runtime setup
      include_tasks: runtime.yml
    - name: Include development setup
      include_tasks: development.yml
